### ISSUE TITLE
Armor Color Change

### ISSUE THREAD

**Issue by Spartan5150** [TarkinII/Core3#8] opened 2017-03-13 05:32 UTC
It appears that Set Color and Set Frame Color are linked options as changing one mimics the change on the other, this is troublesome for armors with more than one color palettes.

Tested on BH/Mabari/Padded/Tantel all with the same results. It should be noted that Mabari/Tantel both have three color change options.

**Comment by stacy19201325** [comment] 2017-03-13 05:37
Yes, both Set Color and Set Frame Color do the same thing.  Only one palette is affected, I think it's palette 2 IIRC.  One of these options was available to me before Kinshi did his update to allow colorization.  After he did that, the second option came up on the radial, but they both do the same palette.  I don't know if there's any way to be able to color the other palette, but I'm confident it's not a Lua thing, if there is.

**Comment by kinshi** [comment] 2017-03-13 16:58
the desired functionality was not present in Tarkin 1.0

Not a bug, this is a feature request.

**Comment by stacy19201325** [comment] 2017-03-13 17:28
Here's the commit for this, for reference: https://github.com/TarkinII/Core3/commit/54935dfca5b1c446be93342c0475b555a2dd9efb

**Comment by Tatwi** [comment] 2017-08-06 14:06
It is possible to add a color option for all colorable parts of armor and clothing. I did this for Hondo for all wearables as a whole, but it can be separated I to just armor or clothing. 

Code reference from Hondo
https://github.com/Tatwi/legend-of-hondo/blob/hondo-master/MMOCoreORB/src/server/zone/objects/tangible/components/WearableObjectMenuComponent.cpp

**Comment by Trakaa** [comment] 2017-08-08 00:36
Fixed in #29

**Comment by stacy19201325** [comment] 2017-08-08 20:27
Fixed.

**Closed by stacy19201325** 2017-08-08 20:27 UTC
Labels: enhancement
